name = "NSInterpolate"
uuid = "c480a481-35d3-4ab9-9d3f-fa60445fa85c"
authors = ["Mark Dransfield"]
version = "1.0.0-DEV"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.11.1"
julia = "1.11"
